# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Daniel Bigler
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Daniel Bigler

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
