# Site settings
title: Danielsaurus
email: hello@danielsaurus.com
author: Daniel Bigler
description: "I'm a dinosaur! Rawr!"
baseurl: ""
url: "http://www.danielsaurusrex.com"
google_analytics: 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
include: ".htaccess"

# gems/plugins

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap