# Site settings
title:              Danielsaurus
author:             Daniel Bigler
email:              hello@danielsaurus.com
description:        "Where Daniel Bigler thinks deep thoughts about stuff and dinosaurs."
tagline:            Not a dinosaur.
url:                http://www.danielsaurus.com
	
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Other stuff
paginate:         1
baseurl:          /

# include: ".htaccess"

# gems/plugins

# gems:
# - jekyll-mentions
# - jemoji
# - jekyll-redirect-from
# - jekyll-sitemap